/*eslint-disable */

export function barChart(mobile, desktop) {
	return `
	<div id='g-OWNERS-box' class='ai2html'>
	<!-- Generated by ai2html v0.61 - 2016-11-03 - 16:01 -->
	<!-- ai file: OWNERS -->

	<style type='text/css' media='screen,print'>
		.g-artboard {
			margin:0 auto;
		}
		@media screen and (max-width: 544px) {
			#g-OWNERS-Artboard_1 {
				display: none;
			}
		}
		@media screen and (min-width: 545px) {
			#g-OWNERS-Artboard_1_copy-graphic {
				display: none;
			}
		}
		@media screen and (max-width: 768px) and (min-width: 545px) {
			#g-OWNERS-Artboard_1 .g-aiPstyle0 {
				line-height: 18px !important;
			}
			#g-OWNERS-Artboard_1 .g-aiPstyle5, #g-OWNERS-Artboard_1 .g-aiPstyle7 {
		    font-size: 13.5px !important;
		    line-height: 16px !important;
			}
			#g-OWNERS-Artboard_1 .g-aiPstyle9, #g-OWNERS-Artboard_1 .g-aiPstyle11 {
		    font-size: 40px !important;
				line-height: 65px !important;
			}
			#g-OWNERS-Artboard_1 .g-aiPstyle10 {
		    font-size: 26px !important;
			}
			#g-OWNERS-Artboard_1 .g-aiPstyle3, #g-OWNERS-Artboard_1 .g-aiPstyle6 {
				line-height: 35px !important;
			}
			#g-OWNERS-Artboard_1 .g-aiPstyle13 {
				font-size: 66px !important;
    		line-height: 70px !important;
			}
			#g-OWNERS-Artboard_1 .g-aiPstyle12 {
		    font-size: 27px !important;
		    line-height: 25px !important;
			}
		}
	</style>


	<!-- Artboard: Artboard_1 -->
	<div id='g-OWNERS-Artboard_1' class='g-artboard g-artboard-v3 ' data-min-width='1024'>
		<style type='text/css' media='screen,print'>
			#g-OWNERS-Artboard_1{
				position:relative;
				overflow:hidden;
			}
			.g-aiAbs{
				position:absolute;
			}
			.g-aiImg{
				display:block;
				width:100% !important;
			}
			#g-OWNERS-Artboard_1 p{
				font-size:13px;
				line-height:18px;
				margin:0;
			}
			#g-OWNERS-Artboard_1 .g-aiPstyle0 {
				font-weight: 700;
				text-shadow: 0 3px 0 rgba(0, 0, 0, 0.2);
				font-size:28px;
				line-height:34px;
				text-align:center;
				letter-spacing:0.02916666666667em;
				color:#ffffff;
			}
			#g-OWNERS-Artboard_1 .g-aiPstyle1 {
				font-size:17px;
				line-height:20px;
				text-align:center;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-OWNERS-Artboard_1 .g-aiPstyle2 {
				font-size:28px;
				line-height:34px;
				letter-spacing:0.02916666666667em;
				color:#ffffff;
			}
			#g-OWNERS-Artboard_1 .g-aiPstyle3 {
				font-size:25px;
				line-height:30px;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-OWNERS-Artboard_1 .g-aiPstyle4 {
				font-size:28px;
				line-height:34px;
				text-align:right;
				letter-spacing:0.02916666666667em;
				color:#ffffff;
			}
			#g-OWNERS-Artboard_1 .g-aiPstyle5 {
				font-size:17px;
				line-height:20px;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-OWNERS-Artboard_1 .g-aiPstyle6 {
				font-size:25px;
				line-height:30px;
				text-align:right;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-OWNERS-Artboard_1 .g-aiPstyle7 {
				font-size:17px;
				line-height:20px;
				text-align:right;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-OWNERS-Artboard_1 .g-aiPstyle8 {
				font-size:35px;
				line-height:42px;
				letter-spacing:0.02916666666667em;
				color:#ffffff;
			}
			#g-OWNERS-Artboard_1 .g-aiPstyle9 {
				font-size:50px;
				line-height:60px;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-OWNERS-Artboard_1 .g-aiPstyle10 {
				font-size:35px;
				line-height:42px;
				text-align:right;
				letter-spacing:0.02916666666667em;
				color:#ffffff;
			}
			#g-OWNERS-Artboard_1 .g-aiPstyle11 {
				font-size:50px;
				line-height:60px;
				text-align:right;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-OWNERS-Artboard_1 .g-aiPstyle12 {
				font-size:35px;
				line-height:42px;
				letter-spacing:0.02916666666667em;
				color:#4e91ff;
			}
			#g-OWNERS-Artboard_1 .g-aiPstyle13 {
				font-weight: 700;
				font-size:90px;
				line-height:108px;
				letter-spacing:0.02416666666667em;
				color:#4e91ff;
			}
			#g-OWNERS-Artboard_1 .g-aiPstyle14 {
				font-size:25px;
				line-height:30px;
				letter-spacing:0.02416666666667em;
				color:#4e91ff;
			}
			.g-aiPtransformed p { white-space: nowrap; }
		</style>
		<div id='g-OWNERS-Artboard_1-graphic'>
			<img id='g-ai0-0'
				class='g-aiImg'
				src='${desktop}'
				/>
			<div id='g-ai0-1' class='g-Layer_1 g-aiAbs' style='top:1.376%;left:49.8684%;width:90.5625%;margin-left:-45.2813%;'>
				<p class='g-aiPstyle0'>一隻狗一生可能需要的基本醫療成本</p>
			</div>
			<div id='g-ai0-2' class='g-Layer_1 g-aiAbs' style='top:4.0909%;left:49.8684%;width:39.3391%;margin-left:-19.6695%;'>
				<p class='g-aiPstyle1'>資料來源： 大群獸醫院</p>
			</div>
			<div id='g-ai0-3' class='g-Layer_1 g-aiAbs' style='top:6.7685%;left:64.3555%;'>
				<p class='g-aiPstyle2'>疫苗費用</p>
			</div>
			<div id='g-ai0-4' class='g-Layer_1 g-aiAbs' style='top:8.2189%;left:64.3555%;'>
				<p class='g-aiPstyle3'>4500 NT$</p>
			</div>
			<div id='g-ai0-5' class='g-Layer_1 g-aiAbs' style='top:9.1487%;right:64.8582%;'>
				<p class='g-aiPstyle4'>驅蟲、整腸費用</p>
			</div>
			<div id='g-ai0-6' class='g-Layer_1 g-aiAbs' style='top:10.2272%;left:64.3555%;'>
				<p class='g-aiPstyle5'>幼犬在約犬齡1個月時需注射各種疾病</p>
			</div>
			<div id='g-ai0-7' class='g-Layer_1 g-aiAbs' style='top:10.5991%;right:64.8582%;'>
				<p class='g-aiPstyle6'>1600 NT$</p>
			</div>
			<div id='g-ai0-8' class='g-Layer_1 g-aiAbs' style='top:11.4172%;left:64.3555%;'>
				<p class='g-aiPstyle5'>的預防疫苗，包含：幼犬疫苗、十合一</p>
			</div>
			<div id='g-ai0-9' class='g-Layer_1 g-aiAbs' style='top:12.6073%;right:64.8933%;'>
				<p class='g-aiPstyle7'>約兩個月大時需進行驅蟲</p>
			</div>
			<div id='g-ai0-10' class='g-Layer_1 g-aiAbs' style='top:12.6073%;left:64.3555%;'>
				<p class='g-aiPstyle5'>疫苗（兩次）、萊姆病疫苗（兩次）、</p>
			</div>
			<div id='g-ai0-11' class='g-Layer_1 g-aiAbs' style='top:13.7974%;right:64.8932%;'>
				<p class='g-aiPstyle7'>與整腸的治療各兩次。</p>
			</div>
			<div id='g-ai0-12' class='g-Layer_1 g-aiAbs' style='top:13.7974%;left:64.3555%;'>
				<p class='g-aiPstyle5'>鞭毛蟲疫苗（兩次）、黴菌疫苗（</p>
			</div>
			<div id='g-ai0-13' class='g-Layer_1 g-aiAbs' style='top:14.9874%;left:64.3555%;'>
				<p class='g-aiPstyle5'>兩次）</p>
			</div>
			<div id='g-ai0-14' class='g-Layer_1 g-aiAbs' style='top:16.2519%;right:65.1423%;'>
				<p class='g-aiPstyle4'>狂犬病疫苗</p>
			</div>
			<div id='g-ai0-15' class='g-Layer_1 g-aiAbs' style='top:17.7023%;right:65.1672%;'>
				<p class='g-aiPstyle6'>3750 NT$</p>
			</div>
			<div id='g-ai0-16' class='g-Layer_1 g-aiAbs' style='top:19.6361%;right:64.3073%;'>
				<p class='g-aiPstyle7'>接下來每年皆需注射狂犬病疫苗，</p>
			</div>
			<div id='g-ai0-17' class='g-Layer_1 g-aiAbs' style='top:20.8262%;right:64.3073%;'>
				<p class='g-aiPstyle7'>持續終身，每劑250元。</p>
			</div>
			<div id='g-ai0-18' class='g-Layer_1 g-aiAbs' style='top:22.5369%;left:64.3555%;'>
				<p class='g-aiPstyle8'>定期驅蟲</p>
			</div>
			<div id='g-ai0-19' class='g-Layer_1 g-aiAbs' style='top:23.913%;left:64.3555%;'>
				<p class='g-aiPstyle9'>90000 NT$</p>
			</div>
			<div id='g-ai0-20' class='g-Layer_1 g-aiAbs' style='top:27.0369%;left:64.3555%;'>
				<p class='g-aiPstyle5'>犬隻需終身接受驅蟲療程（內外寄生</p>
			</div>
			<div id='g-ai0-21' class='g-Layer_1 g-aiAbs' style='top:28.227%;left:64.3555%;'>
				<p class='g-aiPstyle5'>蟲、心絲蟲），每月一次，一次</p>
			</div>
			<div id='g-ai0-22' class='g-Layer_1 g-aiAbs' style='top:29.417%;left:64.3555%;'>
				<p class='g-aiPstyle5'>500元。</p>
			</div>
			<div id='g-ai0-23' class='g-Layer_1 g-aiAbs' style='top:38.8632%;right:64.9195%;'>
				<p class='g-aiPstyle10'>心絲蟲四合一檢測</p>
			</div>
			<div id='g-ai0-24' class='g-Layer_1 g-aiAbs' style='top:40.2392%;right:64.9888%;'>
				<p class='g-aiPstyle11'>13500 NT$</p>
			</div>
			<div id='g-ai0-25' class='g-Layer_1 g-aiAbs' style='top:41.6524%;left:64.3555%;'>
				<p class='g-aiPstyle2'>結紮費用</p>
			</div>
			<div id='g-ai0-26' class='g-Layer_1 g-aiAbs' style='top:43.1028%;left:64.3555%;'>
				<p class='g-aiPstyle3'>1500 NT$</p>
			</div>
			<div id='g-ai0-27' class='g-Layer_1 g-aiAbs' style='top:43.4004%;right:64.9909%;'>
				<p class='g-aiPstyle7'>每年固定執行心絲蟲相關檢測，</p>
			</div>
			<div id='g-ai0-28' class='g-Layer_1 g-aiAbs' style='top:44.5904%;right:64.9909%;'>
				<p class='g-aiPstyle7'>持續終身，每次900元。</p>
			</div>
			<div id='g-ai0-29' class='g-Layer_1 g-aiAbs' style='top:45.0739%;left:64.3555%;'>
				<p class='g-aiPstyle5'>犬齡約4~6個月時應接受結紮手術。</p>
			</div>
			<div id='g-ai0-30' class='g-Layer_1 g-aiAbs' style='top:46.264%;left:64.3555%;'>
				<p class='g-aiPstyle5'>（各縣市政府補助不一，只列出基本</p>
			</div>
			<div id='g-ai0-31' class='g-Layer_1 g-aiAbs' style='top:47.3425%;right:65.1423%;'>
				<p class='g-aiPstyle4'>全身健康檢查</p>
			</div>
			<div id='g-ai0-32' class='g-Layer_1 g-aiAbs' style='top:47.454%;left:64.3555%;'>
				<p class='g-aiPstyle5'>手術麻醉費用）</p>
			</div>
			<div id='g-ai0-33' class='g-Layer_1 g-aiAbs' style='top:48.7929%;right:65.1423%;'>
				<p class='g-aiPstyle6'>8000 NT$</p>
			</div>
			<div id='g-ai0-34' class='g-Layer_1 g-aiAbs' style='top:50.6523%;left:64.3555%;'>
				<p class='g-aiPstyle8'>定期健康檢查</p>
			</div>
			<div id='g-ai0-35' class='g-Layer_1 g-aiAbs' style='top:50.8011%;right:64.8932%;'>
				<p class='g-aiPstyle7'>犬隻7歲後，每2~3年應進行全身所有</p>
			</div>
			<div id='g-ai0-36' class='g-Layer_1 g-aiAbs' style='top:51.9912%;right:64.8932%;'>
				<p class='g-aiPstyle7'>項目的完整健康檢查。一次4000元。</p>
			</div>
			<div id='g-ai0-37' class='g-Layer_1 g-aiAbs' style='top:52.0284%;left:64.3555%;'>
				<p class='g-aiPstyle9'>32000 NT$</p>
			</div>
			<div id='g-ai0-38' class='g-Layer_1 g-aiAbs' style='top:55.1523%;left:64.3555%;'>
				<p class='g-aiPstyle5'>犬隻7歲後，每年皆應接受部分項目的</p>
			</div>
			<div id='g-ai0-39' class='g-Layer_1 g-aiAbs' style='top:56.3424%;left:64.3555%;'>
				<p class='g-aiPstyle5'>定期健康檢查，每次4000元。</p>
			</div>
			<div id='g-ai0-40' class='g-Layer_1 g-aiAbs' style='top:56.6027%;right:65.0872%;'>
				<p class='g-aiPstyle4'>慢性病處方籤</p>
			</div>
			<div id='g-ai0-41' class='g-Layer_1 g-aiAbs' style='top:58.0531%;right:65.0872%;'>
				<p class='g-aiPstyle6'>1600 NT$</p>
			</div>
			<div id='g-ai0-42' class='g-Layer_1 g-aiAbs' style='top:59.0944%;left:64.3555%;'>
				<p class='g-aiPstyle2'>關節退化</p>
			</div>
			<div id='g-ai0-43' class='g-Layer_1 g-aiAbs' style='top:60.0613%;right:64.9909%;'>
				<p class='g-aiPstyle7'>老年後的犬隻容易罹患各種慢性病。</p>
			</div>
			<div id='g-ai0-44' class='g-Layer_1 g-aiAbs' style='top:60.5448%;left:64.3555%;'>
				<p class='g-aiPstyle3'>3000 NT$</p>
			</div>
			<div id='g-ai0-45' class='g-Layer_1 g-aiAbs' style='top:61.2514%;right:64.9909%;'>
				<p class='g-aiPstyle7'>（處方飼料未列入計算）</p>
			</div>
			<div id='g-ai0-46' class='g-Layer_1 g-aiAbs' style='top:62.5158%;left:64.3555%;'>
				<p class='g-aiPstyle5'>老年犬隻的關節問題治療費用。</p>
			</div>
			<div id='g-ai0-47' class='g-Layer_1 g-aiAbs' style='top:64.3381%;right:65.1073%;'>
				<p class='g-aiPstyle10'>關節開刀</p>
			</div>
			<div id='g-ai0-48' class='g-Layer_1 g-aiAbs' style='top:65.7142%;right:65.1073%;'>
				<p class='g-aiPstyle11'>50000 NT$</p>
			</div>
			<div id='g-ai0-49' class='g-Layer_1 g-aiAbs' style='top:68.8753%;right:64.8808%;'>
				<p class='g-aiPstyle7'>關節退化問題的後續醫療成本龐大，</p>
			</div>
			<div id='g-ai0-50' class='g-Layer_1 g-aiAbs' style='top:70.0653%;right:64.8808%;'>
				<p class='g-aiPstyle7'>此處僅計算一個關節的開刀費用。</p>
			</div>
			<div id='g-ai0-51' class='g-Layer_1 g-aiAbs' style='top:74.0075%;left:64.3555%;'>
				<p class='g-aiPstyle2'>安樂死</p>
			</div>
			<div id='g-ai0-52' class='g-Layer_1 g-aiAbs' style='top:75.4579%;left:64.3555%;'>
				<p class='g-aiPstyle3'>4000 NT$</p>
			</div>
			<div id='g-ai0-53' class='g-Layer_1 g-aiAbs' style='top:76.0901%;right:64.8571%;'>
				<p class='g-aiPstyle4'>團體火化</p>
			</div>
			<div id='g-ai0-54' class='g-Layer_1 g-aiAbs' style='top:77.4289%;left:64.3555%;'>
				<p class='g-aiPstyle5'>犬隻晚年若罹患嚴重疾病，飼主可考慮</p>
			</div>
			<div id='g-ai0-55' class='g-Layer_1 g-aiAbs' style='top:77.4289%;left:93.4082%;'>
				<p class='g-aiPstyle5'> </p>
			</div>
			<div id='g-ai0-56' class='g-Layer_1 g-aiAbs' style='top:77.5405%;right:64.8571%;'>
				<p class='g-aiPstyle6'>2000 NT$</p>
			</div>
			<div id='g-ai0-57' class='g-Layer_1 g-aiAbs' style='top:78.619%;left:64.3555%;'>
				<p class='g-aiPstyle5'>進行安樂死。</p>
			</div>
			<div id='g-ai0-58' class='g-Layer_1 g-aiAbs' style='top:79.5487%;right:64.8571%;'>
				<p class='g-aiPstyle7'>死後的火化費用。</p>
			</div>
			<div id='g-ai0-59' class='g-Layer_1 g-aiAbs' style='top:87.3585%;left:24.6094%;'>
				<p class='g-aiPstyle12'>總共花費</p>
			</div>
			<div id='g-ai0-60' class='g-Layer_1 g-aiAbs' style='top:88.8089%;left:24%;'>
				<p class='g-aiPstyle13'>217850</p>
			</div>
			<div id='g-ai0-61' class='g-Layer_1 g-aiAbs' style='top:92.8254%;left:24.3%;'>
				<p class='g-aiPstyle14'>NT$</p>
			</div>
		</div>
	</div>

	<!-- Artboard: Artboard_1_copy -->
	<div id='g-OWNERS-Artboard_1_copy' class='g-artboard g-artboard-v3 ' data-min-width='544' data-max-width='1023'>
		<style type='text/css' media='screen,print'>
			#g-OWNERS-Artboard_1_copy{
				position:relative;
				overflow:hidden;
			}
			.g-aiAbs{
				position:absolute;
			}
			.g-aiImg{
				display:block;
				width:100% !important;
			}
			#g-OWNERS-Artboard_1_copy p{
				font-size:13px;
				line-height:18px;
				margin:0;
			}
			#g-OWNERS-Artboard_1_copy .g-aiPstyle0 {
				font-weight: 700;
				text-shadow: 0 3px 0 rgba(0, 0, 0, 0.2);
				font-size: 17px;
				line-height: 20px;
				text-align:center;
				letter-spacing:0.02916666666667em;
				color:#ffffff;
			}
			#g-OWNERS-Artboard_1_copy .g-aiPstyle1 {
				font-size:14px;
				line-height:20px;
				text-align:center;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-OWNERS-Artboard_1_copy .g-aiPstyle2 {
				font-size: 20px;
				line-height: 22px;
				letter-spacing:0.02916666666667em;
				color:#ffffff;
			}
			#g-OWNERS-Artboard_1_copy .g-aiPstyle3 {
				font-size: 18px;
    		line-height: 25px;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-OWNERS-Artboard_1_copy .g-aiPstyle4 {
				font-size:17px;
				line-height:20px;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-OWNERS-Artboard_1_copy .g-aiPstyle5 {
				font-size: 20px;
    		line-height: 18px;
				letter-spacing:0.02916666666667em;
				color:#ffffff;
			}
			#g-OWNERS-Artboard_1_copy .g-aiPstyle6 {
				font-size: 31px;
    		line-height: 32px;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-OWNERS-Artboard_1_copy .g-aiPstyle7 {
				font-size: 20px;
				line-height: 15px;
				letter-spacing:0.02916666666667em;
				color:#4e91ff;
			}
			#g-OWNERS-Artboard_1_copy .g-aiPstyle8 {
				font-weight: 700;
				font-size: 46px;
    		line-height: 45px;
				letter-spacing:0.02416666666667em;
				color:#4e91ff;
			}
			#g-OWNERS-Artboard_1_copy .g-aiPstyle9 {
				font-size: 16px;
    		line-height: 20px;
				letter-spacing:0.02416666666667em;
				color:#4e91ff;
			}
			.g-aiPtransformed p { white-space: nowrap; }
		</style>
		<div id='g-OWNERS-Artboard_1_copy-graphic'>
			<img id='g-ai1-0'
				class='g-aiImg'
				src='${mobile}'
				/>
			<div id='g-ai1-1' class='g-Layer_1 g-aiAbs' style='top:1.3921%;left:50.7334%;width:170.4708%;margin-left:-85.2354%;'>
				<p class='g-aiPstyle0'>一隻狗一生可能需要的基本醫療成本</p>
			</div>
			<div id='g-ai1-2' class='g-Layer_1 g-aiAbs' style='top:4.1386%;left:50.7335%;width:74.05%;margin-left:-37.025%;'>
				<p class='g-aiPstyle1'>資料來源： 大群獸醫院</p>
			</div>
			<div id='g-ai1-3' class='g-Layer_1 g-aiAbs' style='top:7.2237%;left:41.7412%;'>
				<p class='g-aiPstyle2'>疫苗費用</p>
			</div>
			<div id='g-ai1-4' class='g-Layer_1 g-aiAbs' style='top:8.691%;left:41.7412%;'>
				<p class='g-aiPstyle3'>4500 NT$</p>
			</div>
			<div id='g-ai1-5' class='g-Layer_1 g-aiAbs' style='top:11.0989%;left:41.7412%;'>
				<p class='g-aiPstyle2'>驅蟲、整腸費用</p>
			</div>
			<div id='g-ai1-6' class='g-Layer_1 g-aiAbs' style='top:12.5662%;left:41.7412%;'>
				<p class='g-aiPstyle3'>1600 NT$</p>
			</div>
			<div id='g-ai1-7' class='g-Layer_1 g-aiAbs' style='top:12.7544%;left:43.5795%;'>
				<p class='g-aiPstyle4'> </p>
			</div>
			<div id='g-ai1-8' class='g-Layer_1 g-aiAbs' style='top:15.1999%;left:41.7412%;'>
				<p class='g-aiPstyle2'>狂犬病疫苗</p>
			</div>
			<div id='g-ai1-9' class='g-Layer_1 g-aiAbs' style='top:16.6672%;left:41.7412%;'>
				<p class='g-aiPstyle3'>3750 NT$</p>
			</div>
			<div id='g-ai1-10' class='g-Layer_1 g-aiAbs' style='top:25.5464%;left:41.7412%;'>
				<p class='g-aiPstyle5'>定期驅蟲</p>
			</div>
			<div id='g-ai1-11' class='g-Layer_1 g-aiAbs' style='top:26.9384%;left:41.7412%;'>
				<p class='g-aiPstyle6'>90000 NT$</p>
			</div>
			<div id='g-ai1-12' class='g-Layer_1 g-aiAbs' style='top:39.3166%;left:41.7412%;'>
				<p class='g-aiPstyle5'>心絲蟲四合一檢測</p>
			</div>
			<div id='g-ai1-13' class='g-Layer_1 g-aiAbs' style='top:40.7086%;left:41.7414%;'>
				<p class='g-aiPstyle6'>13500 NT$</p>
			</div>
			<div id='g-ai1-14' class='g-Layer_1 g-aiAbs' style='top:43.869%;left:41.7412%;'>
				<p class='g-aiPstyle2'>結紮費用</p>
			</div>
			<div id='g-ai1-15' class='g-Layer_1 g-aiAbs' style='top:45.3363%;left:41.7412%;'>
				<p class='g-aiPstyle3'>1500 NT$</p>
			</div>
			<div id='g-ai1-16' class='g-Layer_1 g-aiAbs' style='top:47.669%;left:41.7412%;'>
				<p class='g-aiPstyle2'>全身健康檢查</p>
			</div>
			<div id='g-ai1-17' class='g-Layer_1 g-aiAbs' style='top:49.1363%;left:41.7412%;'>
				<p class='g-aiPstyle3'>8000 NT$</p>
			</div>
			<div id='g-ai1-18' class='g-Layer_1 g-aiAbs' style='top:51.469%;left:41.7412%;'>
				<p class='g-aiPstyle5'>定期健康檢查</p>
			</div>
			<div id='g-ai1-19' class='g-Layer_1 g-aiAbs' style='top:52.861%;left:41.7412%;'>
				<p class='g-aiPstyle6'>32000 NT$</p>
			</div>
			<div id='g-ai1-20' class='g-Layer_1 g-aiAbs' style='top:57.9026%;left:41.7412%;'>
				<p class='g-aiPstyle2'>關節退化</p>
			</div>
			<div id='g-ai1-21' class='g-Layer_1 g-aiAbs' style='top:59.3699%;left:41.7412%;'>
				<p class='g-aiPstyle3'>3000 NT$</p>
			</div>
			<div id='g-ai1-22' class='g-Layer_1 g-aiAbs' style='top:61.853%;left:41.7412%;'>
				<p class='g-aiPstyle2'>慢性病處方籤</p>
			</div>
			<div id='g-ai1-23' class='g-Layer_1 g-aiAbs' style='top:63.3204%;left:41.7412%;'>
				<p class='g-aiPstyle3'>1600 NT$</p>
			</div>
			<div id='g-ai1-24' class='g-Layer_1 g-aiAbs' style='top:66.3302%;left:41.7412%;'>
				<p class='g-aiPstyle5'>關節開刀</p>
			</div>
			<div id='g-ai1-25' class='g-Layer_1 g-aiAbs' style='top:67.7223%;left:41.7412%;'>
				<p class='g-aiPstyle6'>50000 NT$</p>
			</div>
			<div id='g-ai1-26' class='g-Layer_1 g-aiAbs' style='top:74.9084%;left:41.7412%;'>
				<p class='g-aiPstyle2'>安樂死</p>
			</div>
			<div id='g-ai1-27' class='g-Layer_1 g-aiAbs' style='top:76.3757%;left:41.7412%;'>
				<p class='g-aiPstyle3'>4000 NT$</p>
			</div>
			<div id='g-ai1-28' class='g-Layer_1 g-aiAbs' style='top:78.8965%;left:41.7412%;'>
				<p class='g-aiPstyle2'>團體火化</p>
			</div>
			<div id='g-ai1-29' class='g-Layer_1 g-aiAbs' style='top:80.3638%;left:41.7412%;'>
				<p class='g-aiPstyle3'>2000 NT$</p>
			</div>
			<div id='g-ai1-30' class='g-Layer_1 g-aiAbs' style='top:86.2707%;left:10.0302%;'>
				<p class='g-aiPstyle7'>總共花費</p>
			</div>
			<div id='g-ai1-31' class='g-Layer_1 g-aiAbs' style='top:87.8885%;left:9.4%;'>
				<p class='g-aiPstyle8'>217850</p>
			</div>
			<div id='g-ai1-32' class='g-Layer_1 g-aiAbs' style='top:91.5756%;left:10.0302%;'>
				<p class='g-aiPstyle9'>NT$</p>
			</div>
		</div>
	</div>

	<!-- End ai2html - 2016-11-03 - 16:01 -->
</div>
	`
}
