/*eslint-disable */

export function lineChart(mobile, desktop) {
	return `<div id='g-animal-ai2html-box' class='ai2html'>
		<!-- Generated by ai2html v0.60 - 2016-11-01 - 14:30 -->
		<!-- ai file: animal-ai2html -->

		<style type='text/css' media='screen,print'>
			.g-artboard {
				margin:0 auto;
			}
			@media screen and (max-width: 544px) {
		    #g-animal-ai2html-_____2 {
		      display: none;
		    }
			}
			@media screen and (min-width: 544px) {
		    #g-animal-ai2html-_____1 {
		      display: none;
		    }
			}
		</style>


		<!-- Artboard: _____1 -->
		<div id='g-animal-ai2html-_____1' class='g-artboard g-artboard-v3 ' data-min-width='544' data-max-width='1023'>
			<style type='text/css' media='screen,print'>
				#g-animal-ai2html-_____1{
					position:relative;
					overflow:hidden;
				}
				.g-aiAbs{
					position:absolute;
				}
				.g-aiImg{
					display:block;
					width:100% !important;
				}
				#g-animal-ai2html-_____1 p{
					font-size:13px;
					line-height:18px;
					margin:0;
				}
				#g-animal-ai2html-_____1 .g-aiPstyle0 {
					font-size:25px;
					line-height:44px;
					letter-spacing:0.02916666666667em;
					color:#ffffff;
				}
				#g-animal-ai2html-_____1 .g-aiPstyle1 {
					font-size:16px;
					line-height:28px;
					letter-spacing:0.02416666666667em;
					color:#ffffff;
				}
				#g-animal-ai2html-_____1 .g-aiPstyle2 {
					font-size:15px;
					line-height:28px;
					letter-spacing:0.02416666666667em;
					color:#4e91ff;
				}
				#g-animal-ai2html-_____1 .g-aiPstyle3 {
					font-size:15px;
					line-height:28px;
					letter-spacing:0.02416666666667em;
					color:#ff6496;
				}
				#g-animal-ai2html-_____1 .g-aiPstyle4 {
					font-size:15px;
					line-height:28px;
					letter-spacing:0.02416666666667em;
					color:#4d4d4d;
				}
				#g-animal-ai2html-_____1 .g-aiPstyle5 {
					font-size:12px;
					line-height:24px;
					letter-spacing:0.02416666666667em;
					color:#ffffff;
				}
				#g-animal-ai2html-_____1 .g-aiPstyle6 {
					font-size:22px;
					line-height:34px;
					letter-spacing:0.02916666666667em;
					color:#5d6e82;
				}
				.g-aiPtransformed p { white-space: nowrap; }
			</style>
			<div id='g-animal-ai2html-_____1-graphic'>
				<img id='g-ai0-0'
					class='g-aiImg'
					src='${mobile}'
					/>
				<div id='g-ai0-1' class='g-___1 g-aiAbs' style='top:5.2813%;left:10.9081%;'>
					<p class='g-aiPstyle0'>全台動物侵害他人案件數</p>
				</div>
				<div id='g-ai0-2' class='g-___1 g-aiAbs' style='top:16.992%;left:10.9081%;'>
					<p class='g-aiPstyle1'>資料來源：農委會 ｜ 單位：件數</p>
				</div>
				<div id='g-ai0-3' class='g-___1 g-aiAbs' style='top:26.9805%;left:22.9628%;'>
					<p class='g-aiPstyle2'>檢舉案件數</p>
				</div>
				<div id='g-ai0-4' class='g-___1 g-aiAbs' style='top:26.9805%;left:59.896%;'>
					<p class='g-aiPstyle3'>稽查案件數</p>
				</div>
				<div id='g-ai0-5' class='g-___1 g-aiAbs' style='top:34.3284%;left:41.4293%;'>
					<p class='g-aiPstyle4'>勸導案件數</p>
				</div>
				<div id='g-ai0-6' class='g-___1 g-aiAbs' style='top:36.6246%;left:74.0023%;'>
					<p class='g-aiPstyle5'>314</p>
				</div>
				<div id='g-ai0-7' class='g-___1 g-aiAbs' style='top:55.4535%;left:19.2664%;'>
					<p class='g-aiPstyle5'>188</p>
				</div>
				<div id='g-ai0-8' class='g-___1 g-aiAbs' style='top:56.946%;left:52.7144%;'>
					<p class='g-aiPstyle5'>202</p>
				</div>
				<div id='g-ai0-9' class='g-___1 g-aiAbs' style='top:67.9679%;left:74.7718%;'>
					<p class='g-aiPstyle5'>101</p>
				</div>
				<div id='g-ai0-10' class='g-___1 g-aiAbs' style='top:69.116%;left:51.4318%;'>
					<p class='g-aiPstyle5'>93</p>
				</div>
				<div id='g-ai0-11' class='g-___1 g-aiAbs' style='top:71.9862%;left:19.1155%;'>
					<p class='g-aiPstyle5'>74</p>
				</div>
				<div id='g-ai0-12' class='g-___1 g-aiAbs' style='top:74.0528%;left:51.4318%;'>
					<p class='g-aiPstyle5'>62</p>
				</div>
				<div id='g-ai0-13' class='g-___1 g-aiAbs' style='top:76.2342%;left:75.5412%;'>
					<p class='g-aiPstyle5'>87</p>
				</div>
				<div id='g-ai0-14' class='g-___1 g-aiAbs' style='top:78.3008%;left:18.859%;'>
					<p class='g-aiPstyle5'>32</p>
				</div>
				<div id='g-ai0-15' class='g-___1 g-aiAbs' style='top:89.4374%;left:10.9081%;'>
					<p class='g-aiPstyle6'>102年</p>
				</div>
				<div id='g-ai0-16' class='g-___1 g-aiAbs' style='top:89.4374%;left:73.7459%;'>
					<p class='g-aiPstyle6'>104年</p>
				</div>
				<div id='g-ai0-17' class='g-___1 g-aiAbs' style='top:89.667%;left:42.1987%;'>
					<p class='g-aiPstyle6'>103年</p>
				</div>
			</div>
		</div>

		<!-- Artboard: _____2 -->
		<div id='g-animal-ai2html-_____2' class='g-artboard g-artboard-v3 ' data-min-width='1024'>
			<style type='text/css' media='screen,print'>
				#g-animal-ai2html-_____2{
					position:relative;
					overflow:hidden;
				}
				.g-aiAbs{
					position:absolute;
				}
				.g-aiImg{
					display:block;
					width:100% !important;
				}
				#g-animal-ai2html-_____2 p{
					font-size:13px;
					line-height:18px;
					margin:0;
				}
				#g-animal-ai2html-_____2 .g-aiPstyle0 {
					font-size:28px;
					line-height:34px;
					letter-spacing:0.02916666666667em;
					color:#ffffff;
				}
				#g-animal-ai2html-_____2 .g-aiPstyle1 {
					font-size:47px;
					line-height:60px;
					letter-spacing:0.02416666666667em;
					color:#4e91ff;
				}
				#g-animal-ai2html-_____2 .g-aiPstyle2 {
					font-size:25px;
					line-height:30px;
					letter-spacing:0.02416666666667em;
					color:#4e91ff;
				}
				#g-animal-ai2html-_____2 .g-aiPstyle3 {
					font-size:17px;
					line-height:20px;
					letter-spacing:0.02416666666667em;
					color:#ffffff;
				}
				#g-animal-ai2html-_____2 .g-aiPstyle4 {
					font-size:20px;
					line-height:24px;
					letter-spacing:0.02416666666667em;
					color:#ffffff;
				}
				#g-animal-ai2html-_____2 .g-aiPstyle5 {
					font-size:17px;
					line-height:20px;
					letter-spacing:0.02416666666667em;
					color:#4e91ff;
				}
				#g-animal-ai2html-_____2 .g-aiPstyle6 {
					font-size:47px;
					line-height:60px;
					letter-spacing:0.02416666666667em;
					color:#ff6496;
				}
				#g-animal-ai2html-_____2 .g-aiPstyle7 {
					font-size:25px;
					line-height:30px;
					letter-spacing:0.02416666666667em;
					color:#ff6496;
				}
				#g-animal-ai2html-_____2 .g-aiPstyle8 {
					font-size:47px;
					line-height:60px;
					letter-spacing:0.02416666666667em;
					color:#4d4d4d;
				}
				#g-animal-ai2html-_____2 .g-aiPstyle9 {
					font-size:17px;
					line-height:20px;
					letter-spacing:0.02416666666667em;
					color:#ff6496;
				}
				#g-animal-ai2html-_____2 .g-aiPstyle10 {
					font-size:25px;
					line-height:30px;
					letter-spacing:0.02416666666667em;
					color:#4d4d4d;
				}
				#g-animal-ai2html-_____2 .g-aiPstyle11 {
					font-size:17px;
					line-height:20px;
					letter-spacing:0.02416666666667em;
					color:#4d4d4d;
				}
				#g-animal-ai2html-_____2 .g-aiPstyle12 {
					font-size:28px;
					line-height:34px;
					letter-spacing:0.02916666666667em;
					color:#5d6e82;
				}
				.g-aiPtransformed p { white-space: nowrap; }
			</style>
			<div id='g-animal-ai2html-_____2-graphic'>
				<img id='g-ai1-0'
					class='g-aiImg'
					src='${desktop}'
					/>
				<div id='g-ai1-1' class='g-___1 g-aiAbs' style='top:12.9249%;left:19.8242%;'>
					<p class='g-aiPstyle0'>全台動物侵害他人案件數</p>
				</div>
				<div id='g-ai1-2' class='g-___1 g-aiAbs' style='top:12.9249%;left:19.8242%;'>
					<p class='g-aiPstyle0'>全台動物侵害他人案件數</p>
				</div>
				<div id='g-ai1-3' class='g-___1 g-aiAbs' style='top:12.9249%;left:75.1953%;'>
					<p class='g-aiPstyle1'>314</p>
				</div>
				<div id='g-ai1-4' class='g-___1 g-aiAbs' style='top:16.1933%;left:83.4961%;'>
					<p class='g-aiPstyle2'>件</p>
				</div>
				<div id='g-ai1-5' class='g-___1 g-aiAbs' style='top:23.77%;left:19.7266%;'>
					<p class='g-aiPstyle3'>資料來源：農委會 ｜ 單位：件數</p>
				</div>
				<div id='g-ai1-6' class='g-___1 g-aiAbs' style='top:38.1806%;left:32.3242%;'>
					<p class='g-aiPstyle4'>188</p>
				</div>
				<div id='g-ai1-7' class='g-___1 g-aiAbs' style='top:41.449%;left:50.9766%;'>
					<p class='g-aiPstyle4'>202</p>
				</div>
				<div id='g-ai1-8' class='g-___1 g-aiAbs' style='top:41.5975%;left:16.3086%;'>
					<p class='g-aiPstyle5'>檢舉案件數</p>
				</div>
				<div id='g-ai1-9' class='g-___1 g-aiAbs' style='top:53.4825%;left:75.1953%;'>
					<p class='g-aiPstyle6'>101</p>
				</div>
				<div id='g-ai1-10' class='g-___1 g-aiAbs' style='top:56.7509%;left:83.4961%;'>
					<p class='g-aiPstyle7'>件</p>
				</div>
				<div id='g-ai1-11' class='g-___1 g-aiAbs' style='top:58.088%;left:50.9766%;'>
					<p class='g-aiPstyle4'>93</p>
				</div>
				<div id='g-ai1-12' class='g-___1 g-aiAbs' style='top:61.9506%;left:32.3242%;'>
					<p class='g-aiPstyle4'>74</p>
				</div>
				<div id='g-ai1-13' class='g-___1 g-aiAbs' style='top:63.4362%;left:76.1719%;'>
					<p class='g-aiPstyle8'>87</p>
				</div>
				<div id='g-ai1-14' class='g-___1 g-aiAbs' style='top:65.0704%;left:50.9766%;'>
					<p class='g-aiPstyle4'>62</p>
				</div>
				<div id='g-ai1-15' class='g-___1 g-aiAbs' style='top:65.219%;left:16.3086%;'>
					<p class='g-aiPstyle9'>稽查案件數</p>
				</div>
				<div id='g-ai1-16' class='g-___1 g-aiAbs' style='top:66.7046%;left:82.5195%;'>
					<p class='g-aiPstyle10'>件</p>
				</div>
				<div id='g-ai1-17' class='g-___1 g-aiAbs' style='top:70.7158%;left:32.1289%;'>
					<p class='g-aiPstyle4'>32</p>
				</div>
				<div id='g-ai1-18' class='g-___1 g-aiAbs' style='top:73.9842%;left:16.3086%;'>
					<p class='g-aiPstyle11'>勸導案件數</p>
				</div>
				<div id='g-ai1-19' class='g-___1 g-aiAbs' style='top:86.9091%;left:27.7344%;'>
					<p class='g-aiPstyle12'>102年</p>
				</div>
				<div id='g-ai1-20' class='g-___1 g-aiAbs' style='top:86.9091%;left:64.2578%;'>
					<p class='g-aiPstyle12'>104年</p>
				</div>
				<div id='g-ai1-21' class='g-___1 g-aiAbs' style='top:87.0577%;left:45.8984%;'>
					<p class='g-aiPstyle12'>103年</p>
				</div>
			</div>
		</div>

		<!-- End ai2html - 2016-11-01 - 14:30 -->
	</div>
	`
}
