/*eslint-disable */

export function barChart(mobile, desktop) {
	return `<div id='g-animal-2-ai2html-box' class='ai2html'>
	<!-- Generated by ai2html v0.60 - 2016-11-01 - 17:41 -->
	<!-- ai file: animal-2-ai2html -->

	<style type='text/css' media='screen,print'>
		.g-artboard {
			margin:0 auto;
		}
		@media screen and (max-width: 544px) {
			#g-animal-2-ai2html-_____1___-graphic {
				display: none;
			}
		}
		@media screen and (min-width: 544px) {
			#g-animal-2-ai2html-_____1 {
				display: none;
			}
		}
	</style>


	<!-- Artboard: _____1 -->
	<div id='g-animal-2-ai2html-_____1' class='g-artboard g-artboard-v3 ' data-min-width='544' data-max-width='1023'>
		<style type='text/css' media='screen,print'>
			#g-animal-2-ai2html-_____1{
				position:relative;
				overflow:hidden;
			}
			.g-aiAbs{
				position:absolute;
			}
			.g-aiImg{
				display:block;
				width:100% !important;
			}
			#g-animal-2-ai2html-_____1 p{
				font-family:nyt-franklin,arial,helvetica,sans-serif;
				font-size:13px;
				line-height:18px;
				margin:0;
			}
			#g-animal-2-ai2html-_____1 .g-aiPstyle0 {
				font-size:27px;
				line-height:42px;
				letter-spacing:0.02916666666667em;
				color:#ffffff;
			}
			#g-animal-2-ai2html-_____1 .g-aiPstyle1 {
				font-size:17px;
				line-height:35px;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-animal-2-ai2html-_____1 .g-aiPstyle2 {
				font-size:17px;
				line-height:35px;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-animal-2-ai2html-_____1 .g-aiPstyle3 {
				font-size:17px;
				line-height:35px;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-animal-2-ai2html-_____1 .g-aiPstyle4 {
				font-size:30px;
				line-height:71px;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-animal-2-ai2html-_____1 .g-aiPstyle5 {
				font-size:51px;
				line-height:122px;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-animal-2-ai2html-_____1 .g-aiPstyle6 {
				font-size:22px;
				line-height:51px;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-animal-2-ai2html-_____1 .g-aiPstyle7 {
				font-size:34px;
				line-height:82px;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-animal-2-ai2html-_____1 .g-aiPstyle8 {
				font-size:17px;
				line-height:41px;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-animal-2-ai2html-_____1 .g-aiPstyle9 {
				font-size:18px;
				line-height:41px;
				letter-spacing:0.02416666666667em;
				color:#4d4d4d;
			}
			#g-animal-2-ai2html-_____1 .g-aiPstyle10 {
				font-size:15px;
				line-height:35px;
				letter-spacing:0.02416666666667em;
				color:#4d4d4d;
			}
			.g-aiPtransformed p { white-space: nowrap; }
		</style>
		<div id='g-animal-2-ai2html-_____1-graphic'>
			<img id='g-ai0-0'
				class='g-aiImg'
				src='${mobile}'
				/>
			<div id='g-ai0-1' class='g-___1 g-aiAbs' style='top:1.7344%;left:3.1249%;'>
				<p class='g-aiPstyle0'>各縣市動保員平均每年</p>
			</div>
			<div id='g-ai0-2' class='g-___1 g-aiAbs' style='top:1.7344%;left:93.7504%;'>
				<p class='g-aiPstyle0'> </p>
			</div>
			<div id='g-ai0-3' class='g-___1 g-aiAbs' style='top:3.9686%;left:3.1249%;'>
				<p class='g-aiPstyle0'>一人須承接案件數</p>
			</div>
			<div id='g-ai0-4' class='g-___1 g-aiAbs' style='top:7.6726%;left:19.4053%;'>
				<p class='g-aiPstyle1'>資料來源： 農委會動保科</p>
			</div>
			<div id='g-ai0-5' class='g-___1 g-aiAbs' style='top:7.6726%;left:80.9078%;'>
				<p class='g-aiPstyle1'> </p>
			</div>
			<div id='g-ai0-6' class='g-___1 g-aiAbs' style='top:9.2601%;left:42.339%;'>
				<p class='g-aiPstyle2'>｜</p>
			</div>
			<div id='g-ai0-7' class='g-___1 g-aiAbs' style='top:9.2601%;left:84.78%;'>
				<p class='g-aiPstyle2'>件</p>
			</div>
			<div id='g-ai0-8' class='g-___1 g-aiAbs' style='top:9.2601%;left:10.0643%;'>
				<p class='g-aiPstyle1'>單位：件/人 </p>
			</div>
			<div id='g-ai0-9' class='g-___1 g-aiAbs' style='top:9.2601%;left:47.8079%;'>
				<p class='g-aiPstyle1'> </p>
			</div>
			<div id='g-ai0-10' class='g-___1 g-aiAbs' style='top:9.2601%;left:62.7339%;'>
				<p class='g-aiPstyle1'> </p>
			</div>
			<div id='g-ai0-11' class='g-___1 g-aiAbs' style='top:9.2895%;left:68.3043%;'>
				<p class='g-aiPstyle3'>=100</p>
			</div>
			<div id='g-ai0-12' class='g-___1 g-aiAbs' style='top:13.0817%;left:28.4373%;'>
				<p class='g-aiPstyle4'>苗栗縣</p>
			</div>
			<div id='g-ai0-13' class='g-___1 g-aiAbs' style='top:15.404%;left:28.4373%;'>
				<p class='g-aiPstyle5'>3100</p>
			</div>
			<div id='g-ai0-14' class='g-___1 g-aiAbs' style='top:20.9013%;left:28.4373%;'>
				<p class='g-aiPstyle6'>新竹市</p>
			</div>
			<div id='g-ai0-15' class='g-___1 g-aiAbs' style='top:22.5769%;left:28.4373%;'>
				<p class='g-aiPstyle7'>1486</p>
			</div>
			<div id='g-ai0-16' class='g-___1 g-aiAbs' style='top:25.0757%;left:51.8752%;'>
				<p class='g-aiPstyle6'>台北市</p>
			</div>
			<div id='g-ai0-17' class='g-___1 g-aiAbs' style='top:26.6925%;left:51.8752%;'>
				<p class='g-aiPstyle7'>1007</p>
			</div>
			<div id='g-ai0-18' class='g-___1 g-aiAbs' style='top:30.2789%;left:81.9934%;'>
				<p class='g-aiPstyle8'>729</p>
			</div>
			<div id='g-ai0-19' class='g-___1 g-aiAbs' style='top:43.3018%;left:4.0625%;'>
				<p class='g-aiPstyle1'>苗栗縣</p>
			</div>
			<div id='g-ai0-20' class='g-___1 g-aiAbs' style='top:43.3018%;left:29.0627%;'>
				<p class='g-aiPstyle1'>新竹市</p>
			</div>
			<div id='g-ai0-21' class='g-___1 g-aiAbs' style='top:43.3018%;left:54.0628%;'>
				<p class='g-aiPstyle1'>台北市</p>
			</div>
			<div id='g-ai0-22' class='g-___1 g-aiAbs' style='top:43.3018%;left:79.0626%;'>
				<p class='g-aiPstyle1'>新竹縣</p>
			</div>
			<div id='g-ai0-23' class='g-___1 g-aiAbs' style='top:49.3282%;left:6.9901%;'>
				<p class='g-aiPstyle8'>627</p>
			</div>
			<div id='g-ai0-24' class='g-___1 g-aiAbs' style='top:49.4164%;left:32.0243%;'>
				<p class='g-aiPstyle8'>597</p>
			</div>
			<div id='g-ai0-25' class='g-___1 g-aiAbs' style='top:50.8275%;left:56.6654%;'>
				<p class='g-aiPstyle8'>409</p>
			</div>
			<div id='g-ai0-26' class='g-___1 g-aiAbs' style='top:50.8275%;left:81.9559%;'>
				<p class='g-aiPstyle8'>392</p>
			</div>
			<div id='g-ai0-27' class='g-___1 g-aiAbs' style='top:61.4986%;left:4.3748%;'>
				<p class='g-aiPstyle1'>高雄市</p>
			</div>
			<div id='g-ai0-28' class='g-___1 g-aiAbs' style='top:61.4986%;left:29.3751%;'>
				<p class='g-aiPstyle1'>台南市</p>
			</div>
			<div id='g-ai0-29' class='g-___1 g-aiAbs' style='top:61.4986%;left:54.3755%;'>
				<p class='g-aiPstyle1'>桃園市</p>
			</div>
			<div id='g-ai0-30' class='g-___1 g-aiAbs' style='top:61.4986%;left:79.3755%;'>
				<p class='g-aiPstyle1'>台中市</p>
			</div>
			<div id='g-ai0-31' class='g-___1 g-aiAbs' style='top:67.7602%;left:7.0245%;'>
				<p class='g-aiPstyle8'>367</p>
			</div>
			<div id='g-ai0-32' class='g-___1 g-aiAbs' style='top:67.7602%;left:31.9838%;'>
				<p class='g-aiPstyle8'>356</p>
			</div>
			<div id='g-ai0-33' class='g-___1 g-aiAbs' style='top:68.5245%;left:57.8902%;'>
				<p class='g-aiPstyle8'>313</p>
			</div>
			<div id='g-ai0-34' class='g-___1 g-aiAbs' style='top:69.2594%;left:82.0155%;'>
				<p class='g-aiPstyle8'>222</p>
			</div>
			<div id='g-ai0-35' class='g-___1 g-aiAbs' style='top:78.4313%;left:4.3748%;'>
				<p class='g-aiPstyle1'>花蓮縣</p>
			</div>
			<div id='g-ai0-36' class='g-___1 g-aiAbs' style='top:78.4313%;left:29.3751%;'>
				<p class='g-aiPstyle1'>金門縣</p>
			</div>
			<div id='g-ai0-37' class='g-___1 g-aiAbs' style='top:78.4313%;left:54.3755%;'>
				<p class='g-aiPstyle1'>澎湖縣</p>
			</div>
			<div id='g-ai0-38' class='g-___1 g-aiAbs' style='top:78.4313%;left:79.3755%;'>
				<p class='g-aiPstyle1'>彰化縣</p>
			</div>
			<div id='g-ai0-39' class='g-___1 g-aiAbs' style='top:82.8702%;left:7.2619%;'>
				<p class='g-aiPstyle9'>190</p>
			</div>
			<div id='g-ai0-40' class='g-___1 g-aiAbs' style='top:82.8702%;left:32.5932%;'>
				<p class='g-aiPstyle9'>145</p>
			</div>
			<div id='g-ai0-41' class='g-___1 g-aiAbs' style='top:82.8702%;left:57.2526%;'>
				<p class='g-aiPstyle9'>140</p>
			</div>
			<div id='g-ai0-42' class='g-___1 g-aiAbs' style='top:82.8702%;left:82.5714%;'>
				<p class='g-aiPstyle9'>129</p>
			</div>
			<div id='g-ai0-43' class='g-___1 g-aiAbs' style='top:84.4871%;left:4.3748%;'>
				<p class='g-aiPstyle10'>新北市</p>
			</div>
			<div id='g-ai0-44' class='g-___1 g-aiAbs' style='top:84.4871%;left:29.3751%;'>
				<p class='g-aiPstyle10'>基隆市</p>
			</div>
			<div id='g-ai0-45' class='g-___1 g-aiAbs' style='top:84.4871%;left:54.3755%;'>
				<p class='g-aiPstyle10'>宜蘭縣</p>
			</div>
			<div id='g-ai0-46' class='g-___1 g-aiAbs' style='top:84.4871%;left:79.3755%;'>
				<p class='g-aiPstyle10'>台東縣</p>
			</div>
			<div id='g-ai0-47' class='g-___1 g-aiAbs' style='top:88.3969%;left:7.5086%;'>
				<p class='g-aiPstyle9'>122</p>
			</div>
			<div id='g-ai0-48' class='g-___1 g-aiAbs' style='top:88.3969%;left:31.8896%;'>
				<p class='g-aiPstyle9'>100</p>
			</div>
			<div id='g-ai0-49' class='g-___1 g-aiAbs' style='top:88.3969%;left:58.8882%;'>
				<p class='g-aiPstyle9'>93</p>
			</div>
			<div id='g-ai0-50' class='g-___1 g-aiAbs' style='top:88.3969%;left:83.8948%;'>
				<p class='g-aiPstyle9'>57</p>
			</div>
			<div id='g-ai0-51' class='g-___1 g-aiAbs' style='top:90.0137%;left:4.3748%;'>
				<p class='g-aiPstyle10'>連江縣</p>
			</div>
			<div id='g-ai0-52' class='g-___1 g-aiAbs' style='top:90.0137%;left:29.3751%;'>
				<p class='g-aiPstyle10'>雲林縣</p>
			</div>
			<div id='g-ai0-53' class='g-___1 g-aiAbs' style='top:90.0137%;left:54.3755%;'>
				<p class='g-aiPstyle10'>南投縣</p>
			</div>
			<div id='g-ai0-54' class='g-___1 g-aiAbs' style='top:90.0137%;left:79.3755%;'>
				<p class='g-aiPstyle10'>嘉義市</p>
			</div>
			<div id='g-ai0-55' class='g-___1 g-aiAbs' style='top:93.9529%;left:34.4411%;'>
				<p class='g-aiPstyle9'>21</p>
			</div>
			<div id='g-ai0-56' class='g-___1 g-aiAbs' style='top:93.9529%;left:59.4946%;'>
				<p class='g-aiPstyle9'>14</p>
			</div>
			<div id='g-ai0-57' class='g-___1 g-aiAbs' style='top:95.5698%;left:29.3751%;'>
				<p class='g-aiPstyle10'>屏東縣</p>
			</div>
			<div id='g-ai0-58' class='g-___1 g-aiAbs' style='top:95.5698%;left:54.3755%;'>
				<p class='g-aiPstyle10'>嘉義縣</p>
			</div>
		</div>
	</div>

	<!-- Artboard: _____1___ -->
	<div id='g-animal-2-ai2html-_____1___' class='g-artboard g-artboard-v3 ' data-min-width='1024'>
		<style type='text/css' media='screen,print'>
			#g-animal-2-ai2html-_____1___{
				position:relative;
				overflow:hidden;
			}
			.g-aiAbs{
				position:absolute;
			}
			.g-aiImg{
				display:block;
				width:100% !important;
			}
			#g-animal-2-ai2html-_____1___ p{
				font-family:nyt-franklin,arial,helvetica,sans-serif;
				font-size:13px;
				line-height:18px;
				margin:0;
			}
			#g-animal-2-ai2html-_____1___ .g-aiPstyle0 {
				font-size:35px;
				line-height:42px;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-animal-2-ai2html-_____1___ .g-aiPstyle1 {
				font-size:28px;
				line-height:34px;
				letter-spacing:0.02916666666667em;
				color:#ffffff;
			}
			#g-animal-2-ai2html-_____1___ .g-aiPstyle2 {
				font-size:80px;
				line-height:96px;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-animal-2-ai2html-_____1___ .g-aiPstyle3 {
				font-size:15px;
				line-height:20px;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-animal-2-ai2html-_____1___ .g-aiPstyle4 {
				font-size:15px;
				line-height:20px;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-animal-2-ai2html-_____1___ .g-aiPstyle5 {
				font-size:15px;
				line-height:20px;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-animal-2-ai2html-_____1___ .g-aiPstyle6 {
				font-size:60px;
				line-height:72px;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-animal-2-ai2html-_____1___ .g-aiPstyle7 {
				font-size:25px;
				line-height:30px;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-animal-2-ai2html-_____1___ .g-aiPstyle8 {
				font-size:40px;
				line-height:48px;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-animal-2-ai2html-_____1___ .g-aiPstyle9 {
				font-size:20px;
				line-height:24px;
				letter-spacing:0.02416666666667em;
				color:#ffffff;
			}
			#g-animal-2-ai2html-_____1___ .g-aiPstyle10 {
				font-size:20px;
				line-height:24px;
				letter-spacing:0.02416666666667em;
				color:#4d4d4d;
			}
			#g-animal-2-ai2html-_____1___ .g-aiPstyle11 {
				font-size:17px;
				line-height:20px;
				letter-spacing:0.02416666666667em;
				color:#4d4d4d;
			}
			.g-aiPtransformed p { white-space: nowrap; }
		</style>
		<div id='g-animal-2-ai2html-_____1___-graphic'>
			<img id='g-ai1-0'
				class='g-aiImg'
				src='${desktop}'
				/>
			<div id='g-ai1-1' class='g-___1 g-aiAbs' style='top:6.3253%;left:12.4023%;'>
				<p class='g-aiPstyle0'>苗栗縣</p>
			</div>
			<div id='g-ai1-2' class='g-___1 g-aiAbs' style='top:8.0321%;left:44.9219%;'>
				<p class='g-aiPstyle1'>各縣市動保員平均每年一人須承接案件數</p>
			</div>
			<div id='g-ai1-3' class='g-___1 g-aiAbs' style='top:8.0321%;left:44.9219%;'>
				<p class='g-aiPstyle1'>各縣市動保員平均每年一人須承接案件數</p>
			</div>
			<div id='g-ai1-4' class='g-___1 g-aiAbs' style='top:10.8434%;left:12.4023%;'>
				<p class='g-aiPstyle2'>3100</p>
			</div>
			<div id='g-ai1-5' class='g-___1 g-aiAbs' style='top:14.8594%;left:48.8757%;'>
				<p class='g-aiPstyle3'>資料來源： 農委會動保科 ｜ 單位：件/人 </p>
			</div>
			<div id='g-ai1-6' class='g-___1 g-aiAbs' style='top:14.8594%;left:79.0714%;'>
				<p class='g-aiPstyle4'>｜</p>
			</div>
			<div id='g-ai1-7' class='g-___1 g-aiAbs' style='top:14.8594%;left:82.4406%;'>
				<p class='g-aiPstyle3'> </p>
			</div>
			<div id='g-ai1-8' class='g-___1 g-aiAbs' style='top:14.8594%;left:87.1048%;'>
				<p class='g-aiPstyle3'> </p>
			</div>
			<div id='g-ai1-9' class='g-___1 g-aiAbs' style='top:14.8594%;left:93.4082%;'>
				<p class='g-aiPstyle4'>件</p>
			</div>
			<div id='g-ai1-10' class='g-___1 g-aiAbs' style='top:14.9598%;left:88.2673%;'>
				<p class='g-aiPstyle5'>=100</p>
			</div>
			<div id='g-ai1-11' class='g-___1 g-aiAbs' style='top:26.1044%;left:12.4023%;'>
				<p class='g-aiPstyle0'>新竹市</p>
			</div>
			<div id='g-ai1-12' class='g-___1 g-aiAbs' style='top:30.7229%;left:12.4023%;'>
				<p class='g-aiPstyle6'>1486</p>
			</div>
			<div id='g-ai1-13' class='g-___1 g-aiAbs' style='top:39.0562%;left:19.7266%;'>
				<p class='g-aiPstyle7'>台北市</p>
			</div>
			<div id='g-ai1-14' class='g-___1 g-aiAbs' style='top:42.3695%;left:19.7266%;'>
				<p class='g-aiPstyle8'>1007</p>
			</div>
			<div id='g-ai1-15' class='g-___1 g-aiAbs' style='top:49.498%;left:28.7478%;'>
				<p class='g-aiPstyle9'>729</p>
			</div>
			<div id='g-ai1-16' class='g-___1 g-aiAbs' style='top:51.004%;left:36.5593%;'>
				<p class='g-aiPstyle9'>627</p>
			</div>
			<div id='g-ai1-17' class='g-___1 g-aiAbs' style='top:51.2048%;left:44.3826%;'>
				<p class='g-aiPstyle9'>597</p>
			</div>
			<div id='g-ai1-18' class='g-___1 g-aiAbs' style='top:54.0161%;left:52.0828%;'>
				<p class='g-aiPstyle9'>409</p>
			</div>
			<div id='g-ai1-19' class='g-___1 g-aiAbs' style='top:54.0161%;left:59.9861%;'>
				<p class='g-aiPstyle9'>392</p>
			</div>
			<div id='g-ai1-20' class='g-___1 g-aiAbs' style='top:54.0161%;left:67.8201%;'>
				<p class='g-aiPstyle9'>367</p>
			</div>
			<div id='g-ai1-21' class='g-___1 g-aiAbs' style='top:54.0161%;left:75.6199%;'>
				<p class='g-aiPstyle9'>356</p>
			</div>
			<div id='g-ai1-22' class='g-___1 g-aiAbs' style='top:55.5221%;left:83.7156%;'>
				<p class='g-aiPstyle9'>313</p>
			</div>
			<div id='g-ai1-23' class='g-___1 g-aiAbs' style='top:57.0281%;left:91.2546%;'>
				<p class='g-aiPstyle9'>222</p>
			</div>
			<div id='g-ai1-24' class='g-___1 g-aiAbs' style='top:75.4016%;left:4.4922%;'>
				<p class='g-aiPstyle3'>苗栗縣</p>
			</div>
			<div id='g-ai1-25' class='g-___1 g-aiAbs' style='top:75.4016%;left:12.3047%;'>
				<p class='g-aiPstyle3'>新竹市</p>
			</div>
			<div id='g-ai1-26' class='g-___1 g-aiAbs' style='top:75.4016%;left:20.1172%;'>
				<p class='g-aiPstyle3'>台北市</p>
			</div>
			<div id='g-ai1-27' class='g-___1 g-aiAbs' style='top:75.4016%;left:27.9297%;'>
				<p class='g-aiPstyle3'>新竹縣</p>
			</div>
			<div id='g-ai1-28' class='g-___1 g-aiAbs' style='top:75.4016%;left:35.7422%;'>
				<p class='g-aiPstyle3'>高雄市</p>
			</div>
			<div id='g-ai1-29' class='g-___1 g-aiAbs' style='top:75.4016%;left:43.5547%;'>
				<p class='g-aiPstyle3'>台南市</p>
			</div>
			<div id='g-ai1-30' class='g-___1 g-aiAbs' style='top:75.4016%;left:51.3672%;'>
				<p class='g-aiPstyle3'>桃園市</p>
			</div>
			<div id='g-ai1-31' class='g-___1 g-aiAbs' style='top:75.4016%;left:59.1797%;'>
				<p class='g-aiPstyle3'>台中市</p>
			</div>
			<div id='g-ai1-32' class='g-___1 g-aiAbs' style='top:75.4016%;left:66.9922%;'>
				<p class='g-aiPstyle3'>花蓮縣</p>
			</div>
			<div id='g-ai1-33' class='g-___1 g-aiAbs' style='top:75.4016%;left:74.8047%;'>
				<p class='g-aiPstyle3'>金門縣</p>
			</div>
			<div id='g-ai1-34' class='g-___1 g-aiAbs' style='top:75.4016%;left:82.6172%;'>
				<p class='g-aiPstyle3'>澎湖縣</p>
			</div>
			<div id='g-ai1-35' class='g-___1 g-aiAbs' style='top:75.4016%;left:90.4297%;'>
				<p class='g-aiPstyle3'>彰化縣</p>
			</div>
			<div id='g-ai1-36' class='g-___1 g-aiAbs' style='top:85.8434%;left:13.2068%;'>
				<p class='g-aiPstyle10'>190</p>
			</div>
			<div id='g-ai1-37' class='g-___1 g-aiAbs' style='top:85.8434%;left:21.1228%;'>
				<p class='g-aiPstyle10'>145</p>
			</div>
			<div id='g-ai1-38' class='g-___1 g-aiAbs' style='top:85.8434%;left:28.8289%;'>
				<p class='g-aiPstyle10'>140</p>
			</div>
			<div id='g-ai1-39' class='g-___1 g-aiAbs' style='top:85.8434%;left:36.741%;'>
				<p class='g-aiPstyle10'>129</p>
			</div>
			<div id='g-ai1-40' class='g-___1 g-aiAbs' style='top:85.8434%;left:44.5339%;'>
				<p class='g-aiPstyle10'>122</p>
			</div>
			<div id='g-ai1-41' class='g-___1 g-aiAbs' style='top:85.8434%;left:52.1531%;'>
				<p class='g-aiPstyle10'>100</p>
			</div>
			<div id='g-ai1-42' class='g-___1 g-aiAbs' style='top:85.8434%;left:60.59%;'>
				<p class='g-aiPstyle10'>93</p>
			</div>
			<div id='g-ai1-43' class='g-___1 g-aiAbs' style='top:85.8434%;left:68.4045%;'>
				<p class='g-aiPstyle10'>57</p>
			</div>
			<div id='g-ai1-44' class='g-___1 g-aiAbs' style='top:85.8434%;left:76.3879%;'>
				<p class='g-aiPstyle10'>21</p>
			</div>
			<div id='g-ai1-45' class='g-___1 g-aiAbs' style='top:85.8434%;left:84.217%;'>
				<p class='g-aiPstyle10'>14</p>
			</div>
			<div id='g-ai1-46' class='g-___1 g-aiAbs' style='top:89.0562%;left:12.3047%;'>
				<p class='g-aiPstyle11'>新北市</p>
			</div>
			<div id='g-ai1-47' class='g-___1 g-aiAbs' style='top:89.0562%;left:20.1172%;'>
				<p class='g-aiPstyle11'>基隆市</p>
			</div>
			<div id='g-ai1-48' class='g-___1 g-aiAbs' style='top:89.0562%;left:27.9297%;'>
				<p class='g-aiPstyle11'>宜蘭縣</p>
			</div>
			<div id='g-ai1-49' class='g-___1 g-aiAbs' style='top:89.0562%;left:35.7422%;'>
				<p class='g-aiPstyle11'>台東縣</p>
			</div>
			<div id='g-ai1-50' class='g-___1 g-aiAbs' style='top:89.0562%;left:43.5547%;'>
				<p class='g-aiPstyle11'>連江縣</p>
			</div>
			<div id='g-ai1-51' class='g-___1 g-aiAbs' style='top:89.0562%;left:51.3672%;'>
				<p class='g-aiPstyle11'>雲林縣</p>
			</div>
			<div id='g-ai1-52' class='g-___1 g-aiAbs' style='top:89.0562%;left:59.1797%;'>
				<p class='g-aiPstyle11'>南投縣</p>
			</div>
			<div id='g-ai1-53' class='g-___1 g-aiAbs' style='top:89.0562%;left:66.9922%;'>
				<p class='g-aiPstyle11'>嘉義市</p>
			</div>
			<div id='g-ai1-54' class='g-___1 g-aiAbs' style='top:89.0562%;left:74.8047%;'>
				<p class='g-aiPstyle11'>屏東縣</p>
			</div>
			<div id='g-ai1-55' class='g-___1 g-aiAbs' style='top:89.0562%;left:82.6172%;'>
				<p class='g-aiPstyle11'>嘉義縣</p>
			</div>
		</div>
	</div>

	<!-- End ai2html - 2016-11-01 - 17:41 -->
</div>
	`
}
